apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-frontend-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-frontend-pod
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.port }}

  egress:
    - to:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}-backend-pod
      
      ports:
        - protocol: TCP
          port: {{ .Values.backend.port }}