apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-backend-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app:  {{ .Release.Name }}-backend-pod
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Release.Name }}-frontend-pod
      ports:
        - protocol: TCP
          port: {{ .Values.backend.port }}