apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  labels:
    app: {{ .Release.Name }}-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend-pod

  template:
    metadata:
      name: {{ .Release.Name }}-backend-pod
      labels:
        app: {{ .Release.Name }}-backend-pod

    spec:
      containers:
        - name: {{ .Release.Name }}-backend-container
          image:  "{{ .Values.backend.image }}:{{ .Values.backend.backendTag }}"
          ports:
            - containerPort: {{ .Values.backend.port}}