name: Build and Deploy to GKE

on:
  push:
    branches:
      - "frontend"
      - "backend"

env:
  frontend-tag: "v1"
  backend-tag: "v1"

jobs:
  Frontend-docker-image:
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/frontend'
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"

      - id: "auth"
        name: "Authentication"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Configure Docker"
        run: |-
          gcloud --quiet auth configure-docker
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: "Build Frontend Docker image"
        run: |-
          docker build -t frontend ./frontend

      - name: "Tag Frontend Docker image"
        run: |-
          docker tag frontend us-central1-docker.pkg.dev/testing-336413/genesys/frontend:${{ github.sha }}

      - name: Set the Frontend SHA
        run: |
          echo "{frontend-tag}=${{ github.sha }}" >> $GITHUB_ENV

      - name: "Push Frontend Docker image"
        run: |-
          docker push us-central1-docker.pkg.dev/testing-336413/genesys/frontend:${{ github.sha }}

  Backend-docker-image:
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/backend'
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"
        with:
          ref: backend

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Configure Docker"
        run: |-
          gcloud --quiet auth configure-docker
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: "Build Backend Docker image"
        run: |-
          docker build -t backend ./backend

      - name: "Tag Backend Docker image"
        run: |-
          docker tag backend us-central1-docker.pkg.dev/testing-336413/genesys/backend:${{ github.sha }}

      - name: Set the Frontend SHA
        run: |
          echo "{backend-tag}=${{ github.sha }}" >> $GITHUB_ENV

      - name: "Push Backend Docker image"
        run: |-
          docker push us-central1-docker.pkg.dev/testing-336413/genesys/backend:${{ github.sha }}

  