name: Run Terraform Apply

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  
  if_merged:

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
    - run: |
        echo The PR was merged
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Run a multi-line script
      run: |
        echo "Do something here"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform version
      run: terraform --version

    - name: Terraform Init
      run: terraform init 
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Terraform Format
      run: terraform fmt -list=true -write=false -diff=true -check=true

    - name: Terraform Plan
      run: terraform plan 
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}